"""initial migrate

Revision ID: cadd38771434
Revises: 
Create Date: 2023-04-15 23:20:15.971563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadd38771434'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulkdeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_date', sa.Date(), nullable=True),
    sa.Column('security_code', sa.Integer(), nullable=True),
    sa.Column('security_name', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=True),
    sa.Column('deal_type', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bulkdeals')
    # ### end Alembic commands ###
