"""created date

Revision ID: e70ee4e4e759
Revises: cadd38771434
Create Date: 2023-04-16 00:36:00.627218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70ee4e4e759'
down_revision = 'cadd38771434'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulkdeals', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulkdeals', 'created_at')
    # ### end Alembic commands ###
