version: "1.1"
services:

  app:
    build: ./web_app
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./web_app/.env

  scraper:
    build: ./scraper
    ports:
      - 8001:9000
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./scraper/.env

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - .db-data:/var/lib/mysql
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10



