"""default changes

Revision ID: 5ddcfed71bf4
Revises: 
Create Date: 2023-04-15 21:16:54.319320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ddcfed71bf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(64), nullable=True),
    sa.Column('password', sa.String(64), nullable=True),
    sa.Column('first_name', sa.String(64), nullable=True),
    sa.Column('last_name', sa.String(64), nullable=True),
    sa.Column('address', sa.String(64), nullable=True),
    sa.Column('city', sa.String(64), nullable=True),
    sa.Column('state', sa.String(64), nullable=True),
    sa.Column('pincode', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
